#!/bin/bash
# CAWA environment setup for TCVW (uses SNAP)
# usage:  . mytcwv

export CAWA_INST=/home/cvop/cawa-inst
export CAWA_LOG=$CAWA_INST/log

export CAWA_PRODUCTION_JAR=$CAWA_INST/lib/cpt.jar
#export SNAPTEST_BEAM_VERSION=snap-2.0-installed
export CAWA_BEAM_VERSION=snap-2.0-bundle
export CAWA_CALVALUS_VERSION=calvalus-snap

export PYTHONPATH=$CAWA_INST:$CAWA_INST/src:$PYTHONPATH
export PATH=$CAWA_INST/bin:$CAWA_PROCESSING_DIR/bin:$JAVA_DIR/bin:$PATH
PS1="\[\e]0;\u@\h: \w\a\]\[\e[1;32m\]\u \[\e[1;34m\]\w\[\e[0m\] \[\e[0;31m\](CAWA-TCWV)\[\e[0m\]$ "

echo "using Calvalus        $CAWA_CALVALUS_VERSION"
echo "using SNAP            $CAWA_BEAM_VERSION"
echo "using CAWA instance   $CAWA_INST"
